#!/bin/bash
set -euo pipefail

#### set default paths and values

version=4.0
OUTPUTDIR="$(pwd)/needLR_output"
#temp=$(mktemp -u -t needlr.temp.XXXXX)

thisscript=$(realpath "$0")
scriptpath=${thisscript%/*}
#refloc=REFLOCPATH
refloc=/home/mgaley/needLR_manu/needLR/backend_files
FILTERPASS=0 #this setting is to include non-passing variants or not. default is to filter nothing.
run1kg=1 #this setting determines whether or not to run 1kg specific annotation scripts or use a custom control set
THREADS=1
ANALYSISREGION="All"
DATA1KG="$refloc/UWONT_500_sniffles_2.6.2_preproc2_T31_v4.2.2.vcf.gz"


# truvari parameters

truvari_k="common"
truvari_s=50
truvari_S=10000000
truvari_r=2000
truvari_p=0
truvari_P=0.2
truvari_O=0.2

# other parameters

RUNSUBPOPS=0
MERGECONTROLS=0
MELTCONTROLS=0

# annotation filenames

GENES="$refloc/bed_files/PROTEIN_CODING_GENE_gencode.v45.annotation_5kb_slop.bed"
UTR="$refloc/bed_files/ENSEMBL_CANONICAL_PROTEIN_CODING_UTR_gencode.v45.annotation.bed"
CDS="$refloc/bed_files/ENSEMBL_CANONICAL_EXON_in_PROTEIN_CODING_GENE_NO_UTR_gencode.v45.annotation.sorted.bed"
OMIM_GENES="$refloc/bed_files/OMIM.20260129.sanitized.name_indexed.csv"
GENCC="$refloc/bed_files/gencc-clean-sorted-20260326.csv"
#HPO="$refloc/bed_files/HPO_genes_to_phenotype_cut.txt"
PLI="$refloc/bed_files/gnomAD_v4.1_constraint_CURATED.csv"
OREGANNO="$refloc/bed_files/ORegAnno.bed"
HG38_REGIONS="$refloc/bed_files/hg38.centromeres.pericentromeres.telomeres.bed"
VAMOS="$refloc/bed_files/from_SG_STR_VNTR_original_motifs.set148_cut.sorted.bed"
VAMOSEXPAND="$refloc/bed_files/vamos.slop.hg38.sorted.bed"
SEGDUPS="$refloc/bed_files/SEGDUPS_GIAB_v3.3.labeled.bed"
HOMOPOLYMERS="$refloc/bed_files/gus_homemade_homopolymers_ge50_nodecoy.bed"
REPEAT_MASKER="$refloc/bed_files/UCSC_hg38_Repeats_RepeatMasker.bed"
DEFRABB_HICONF="$refloc/bed_files/GRCh38_HG002-T2TQ100-V1.0_stvar.benchmark.labeled.bed"
GAPS="$refloc/bed_files/UCSC_hg38_Mapping_and_Sequencing_Gap.labeled.bed"
GENOME_FILE="$refloc/bed_files/hg38.chrom.sizes.txt"

ALLANNOTATIONLIST=( omim gencc hpo pli utr cds oreganno tre mapflags hiconf )
NSUBGROUPS=1

declare -A INFOCOLTEXT

INFOCOLTEXT[End_Pos]='##INFO=<ID=End_Pos,Number=1,Type=Integer,Description="End position of the SV">'
INFOCOLTEXT[SVLEN]='##INFO=<ID=SVLEN,Number=1,Type=Integer,Description="SV length">'
INFOCOLTEXT[SVTYPE]='##INFO=<ID=SVTYPE,Number=1,Type=String,Description="SV type">'
INFOCOLTEXT[Query_ID]='##INFO=<ID=Query_ID,Number=1,Type=String,Description="Query sample ID">'
INFOCOLTEXT[Control_support]='##INFO=<ID=Control_support,Number=.,Type=String,Description="control samples sharing the SV">' 
INFOCOLTEXT[Allele_Freq_ALL_Control]='##INFO=<ID=Allele_Freq_ALL_Control,Number=1,Type=Float,Description="Allele frequency of the SV in the control sample cohort">'
INFOCOLTEXT[Genes]='##INFO=<ID=Genes,Number=.,Type=String,Description="Genes overlapped by the SV (gencode v45, +/-5kb)">'
INFOCOLTEXT[Pop_Count_ALL]='##INFO=<ID=Pop_Count_ALL,Number=1,Type=Integer,Description="Count of samples carrying the SV (controls)">'
INFOCOLTEXT[Pop_Freq_ALL]='##INFO=<ID=Pop_Freq_ALL,Number=1,Type=Float,Description="Proportion of control samples carrying the SV (controls)">'
INFOCOLTEXT[Allele_Count_ALL]='##INFO=<ID=Allele_Count_ALL,Number=1,Type=Integer,Description="count of alleles carrying the SV (controls)">'
INFOCOLTEXT[Allele_Freq_ALL]='##INFO=<ID=Allele_Freq_ALL,Number=1,Type=Float,Description="control allele frequency (controls)">'
INFOCOLTEXT[GT_homWT]='##INFO=<ID=GT_homWT,Number=1,Type=Integer,Description="Count of homozygous genotypes matching the reference in the control dataset">'
INFOCOLTEXT[GT_het]='##INFO=<ID=GT_het,Number=1,Type=Integer,Description="Count of heterozygous genotypes in the control dataset">'
INFOCOLTEXT[GT_homVAR]='##INFO=<ID=GT_homVAR,Number=1,Type=Integer,Description="Count of homozygous genotypes supporting the SV in the control dataset">'
INFOCOLTEXT[p]='##INFO=<ID=p,Number=1,Type=Float,Description="Frequency of WT allele in control population">'
INFOCOLTEXT[q]='##INFO=<ID=q,Number=1,Type=Float,Description="Frequency of SV alt allele in control population">'
INFOCOLTEXT[HWE]='##INFO=<ID=HWE,Number=1,Type=String,Description="HWE Equilibrium status, TRUE or FALSE">'
##single samples and probands
INFOCOLTEXT[Genotype]='##INFO=<ID=Genotype,Number=1,Type=String,Description="Genotype of the SV in the query sample">'
INFOCOLTEXT[Alt_Reads]='##INFO=<ID=Alt_Reads,Number=1,Type=Integer,Description="Number of reads in the query sample supporting the SV">'
INFOCOLTEXT[Ref_Reads]='##INFO=<ID=Ref_Reads,Number=1,Type=Integer,Description="Number of reference reads in the query sample at the SV locus">'
INFOCOLTEXT[Total_Reads]='##INFO=<ID=Total_Reads,Number=1,Type=Integer,Description="Total number of reads in the query sample at the SV locus">'
##duos and trios only
INFOCOLTEXT[Inheritance]='##INFO=<ID=Inheritance,Number=1,Type=String,Description="Inheritance pattern, one of de_novo, inherited, maternal, or paternal">'
INFOCOLTEXT[Parental_GT]='##INFO=<ID=Parental_GT,Number=1,Type=String,Description="Parental genotype">' 
INFOCOLTEXT[Parental_Alt_Reads]='##INFO=<ID=Parental_Alt_Reads,Number=1,Type=Integer,Description="Parental supporting reads">'
INFOCOLTEXT[Parental_Ref_Reads]='##INFO=<ID=Parental_Ref_Reads,Number=1,Type=Integer,Description="Parental reference reads">'
INFOCOLTEXT[Parental_Total_Reads]='##INFO=<ID=Parental_Total_Reads,Number=1,Type=Integer,Description="Parental total number of reads at SV locus">'
INFOCOLTEXT[Maternal_GT]='##INFO=<ID=Maternal_GT,Number=1,Type=String,Description="Maternal genotype">' 
INFOCOLTEXT[Maternal_Alt_Reads]='##INFO=<ID=Maternal_Alt_Reads,Number=1,Type=Integer,Description="Maternal supporting reads">'
INFOCOLTEXT[Maternal_Ref_Reads]='##INFO=<ID=Maternal_Ref_Reads,Number=1,Type=Integer,Description="Maternal reference reads">'
INFOCOLTEXT[Maternal_Total_Reads]='##INFO=<ID=Maternal_Total_Reads,Number=1,Type=Integer,Description="Maternal total number of reads at SV locus">'
INFOCOLTEXT[Paternal_GT]='##INFO=<ID=Paternal_GT,Number=1,Type=String,Description="Paternal genotype">' 
INFOCOLTEXT[Paternal_Alt_Reads]='##INFO=<ID=Paternal_Alt_Reads,Number=1,Type=Integer,Description="Paternal supporting reads">'
INFOCOLTEXT[Paternal_Ref_Reads]='##INFO=<ID=Paternal_Ref_Reads,Number=1,Type=Integer,Description="Paternal reference reads">'
INFOCOLTEXT[Paternal_Total_Reads]='##INFO=<ID=Paternal_Total_Reads,Number=1,Type=Integer,Description="Paternal total number of reads at SV locus">'
##cohorts only
INFOCOLTEXT[Cohort_support]='##INFO=<ID=Cohort_support,Number=.,Type=String,Description="Cohort samples carrying the SV">'
INFOCOLTEXT[Pop_Count_Cohort]='##INFO=<ID=Pop_Count_Cohort,Number=1,Type=Integer,Description="Number of cohort individuals carrying the SV">'
INFOCOLTEXT[Pop_Freq_Cohort]='##INFO=<ID=Pop_Freq_Cohort,Number=1,Type=Float,Description="Proportion of cohort individuals carrying the SV">'
INFOCOLTEXT[Allele_Count_Cohort]='##INFO=<ID=Allele_Count_Cohort,Number=1,Type=Integer,Description="Number of cohort alleles carrying the SV">'
INFOCOLTEXT[Allele_Freq_Cohort]='##INFO=<ID=Allele_Freq_Cohort,Number=1,Type=Float,Description="Allele frequency of the SV in the cohort">'
INFOCOLTEXT[GT_coh_homWT]='##INFO=<ID=GT_coh_homWT,Number=1,Type=Integer,Description="Count of homozygous genotypes matching the reference in the cohort">'
INFOCOLTEXT[GT_coh_het]='##INFO=<ID=GT_coh_het,Number=1,Type=Integer,Description="Count of heterozygous genotypes in the cohort">'
INFOCOLTEXT[GT_coh_homVAR]='##INFO=<ID=GT_coh_homVAR,Number=1,Type=Integer,Description="Count of homozygous genotypes supporting the SV in the cohort">'
##annotations
INFOCOLTEXT[OMIM_phenotype]='##INFO=<ID=OMIM_phenotype,Number=.,Type=String,Description="OMIM phenotypes associated with any gene the SV overlaps (OMIM 20260129)">'
INFOCOLTEXT[OMIM_MOI]='##INFO=<ID=OMIM_MOI,Number=.,Type=String,Description="Mode of inheritance associated with phenotypes and genes the SV overlaps (OMIM 20260129)">'
INFOCOLTEXT[GENCC_phenotype]='##INFO=<ID=GENCC_phenotype,Number=.,Type=String,Description="GenCC phenotypes for overlapping genes (GenCC 20250510)">'
INFOCOLTEXT[GENCC_support]='##INFO=<ID=GENCC_support,Number=.,Type=String,Description="Support level(s) for GenCC phenotypes for overlapping genes (GenCC 20250510)">'
INFOCOLTEXT[GENCC_MOI]='##INFO=<ID=GENCC_MOI,Number=.,Type=String,Description="Mode of inheritance for GenCC phenotypes for overlapping genes (GenCC 20250510)">'
INFOCOLTEXT[HPO_terms]='##INFO=<ID=HPO_terms,Number=.,Type=String,Description="HPO terms for overlapping genes (OMIM 20260129)">'
INFOCOLTEXT[pLI]='##INFO=<ID=pLI,Number=.,Type=String,Description="pLI scores from gnomAD v4.1">'
INFOCOLTEXT[UTR]='##INFO=<ID=UTR,Number=1,Type=String,Description="SV overlaps a UTR (gencode v45)">'
INFOCOLTEXT[CDS]='##INFO=<ID=CDS,Number=1,Type=String,Description="SV overlaps a coding exon (gencode v45)">'
INFOCOLTEXT[ORegAnno]='##INFO=<ID=ORegAnno,Number=1,Type=String,Description="SV overlaps a regulatory element (ORegAnno)">'
INFOCOLTEXT[TRE]='##INFO=<ID=TRE,Number=1,Type=String,Description="SV overlaps a tandem repeat region (VAMOS, n=148)">'
INFOCOLTEXT[Centromeric]='##INFO=<ID=Centromeric,Number=1,Type=String,Description="SV overlaps a centromeric region (UCSC hg38)">'
INFOCOLTEXT[Pericentromeric]='##INFO=<ID=Pericentromeric,Number=1,Type=String,Description="SV overlaps a pericentromeric region (+/-5Mb)">'
INFOCOLTEXT[Telomeric]='##INFO=<ID=Telomeric,Number=1,Type=String,Description="SV overlaps a telomeric region (5Mb from chromosome end)">'
INFOCOLTEXT[Segdup]='##INFO=<ID=Segdup,Number=1,Type=String,Description="SV overlaps a segmental duplication (GIAB v3.3)">'
INFOCOLTEXT[Repeat]='##INFO=<ID=Repeat,Number=1,Type=String,Description="SV overlaps a repeat region (UCSC RepeatMasker)">'
INFOCOLTEXT[Gap]='##INFO=<ID=Gap,Number=1,Type=String,Description="SV overlaps an hg38 assembly gap (UCSC)">'
INFOCOLTEXT[Homopolymer]='##INFO=<ID=Homopolymer,Number=1,Type=String,Description="SV overlaps a homopolymeric region >=50bp">'
INFOCOLTEXT[HiConf]='##INFO=<ID=HiConf,Number=1,Type=String,Description="SV fully contained in a high-confidence region (GIAB T2TQ100-V1.0)">'


#TOTAL_SAMPLES=500 this is now defined when providing a custom control or choosing the default
#AFR=163
#AMR=67
#EAS=95
#EUR=72
#SAS=103 # these are also defined when providing a control

## fancy printing
#bold=$(tput bold)
#normal=$(tput sgr0)
bold=""
normal=""



############################# help and helper functions #######################################################################################
##### help functions

help() {
  echo """

  ${bold}needLR v 4.0${normal}
  ---------------------------------------------------------------

  Usage: needLR {subcommand} <options> {input}

  
  Subcommands:
    
    annotate    :  basic mode: Compares one or more query vcfs to a pre-merged, multisample 
                   vcf of 500 1KGP samples or a user supplied merged control VCF and annotates
                   the SVs in the query individual(s). Multisample query VCFs are summarized and
                   do not include genotype information in the output.

    comparator  :  Compares a single query sample and one or two parental samples to a pre-merged,
                    multisample vcf of 500 1KGP samples and annotates the SVs in the query individual. 
                   This function uniquely annotates the SVs from the query vcf as being "inherited", 
                   "maternal", "paternal", "de_novo", or "uncertain" based on SVs from the parental vcf(s).
    bed         :  Applies needLR annotations to any sorted bed file


  Global option:
   -B                     : [ path to folder containing backend files for non-conda custom installation ]
   -T                     : [ additional CPU threads to pass to bcftools ]
   -R                     : [ restrict analysis to region (e.g. chr1:23456-34567) ]
   -H                     : [ this helpful help ]
  """
}


comparatorHelp() {
    echo """
    Usage: needLR comparator -p {path/to/maternal/vcf.gz},{path/to/paternal/vcf.gz} <additional options> {input}
        **OR**
           needLR comparator -p {path/to/parental/vcf.gz <additional options> {input}
    
    Required:

    positional parameter 1 : [ the path to proband VCF[.gz] ]
    -P                     : [ full path to one or two parental VCFs[gz], separated by commas.
                               maternal vcf is assumed to be first vcf ]
    
    Additional options:
    -O                     : [ output directory name (default is needLR_output relative to current directory) ]
    -C                     : [ full path to a gzipped and tabix indexed control cohort vcf ]
    -T                     : [ additional CPU threads to pass to bcftools ] 
    -S                     : [ subpopulation names and counts, provided as a .csv/.tsv file or a , separated list of : pairs ]

    """
}

annotateHelp() {
    echo """
    Usage: needLR annotate <options> {input}
    
    Required:

    positional parameter 1 : [ the path to input VCF[.gz], not required if using -l or -q ]

    
    Additional options:
    -T     : [ additional CPU threads to pass to bcftools ] 
    -C     : [ full path to a control cohort vcf ]
    -L     : [ .txt file list of full file paths to gzipped query vcfs ]
    -Q     : [ full path to a truvari-merged query cohort vcf ]
    -O     : [ output directory name (default is needLR_output relative to current directory) ]
    -S     : [ subpopulation names and counts, provided as a .csv/.tsv file or a , separated list of : pairs ]

    General Annotation options:
    --all    :   [ annotate VCF with all available options listed below (default TRUE) ]
    
    a la Carte:

    Gene Annotation options:
    --omim   :   [ annotate VCF with OMIM phenotypes and modes of inheritance (default FALSE) ]
    --hpo    :   [ annotate VCF with OMIM phenotype associated HPO terms (default FALSE) ]
    --gencc  :   [ annotate VCF with GENCC phenotypes, level of support, and modes of inheritance (default FALSE) ]
    --pli    :   [ annotate VCF with probability of loss-of-function intolerance (pLI) scores from gnomADg v4.1 (default FALSE) ]

    Position Annotation options:
    --utr       :   [ annotate SV UTR overlap (gencodev45) (default FALSE) ]
    --cds       :   [ annotate SV coding exon overlap (gencodev45) (default FALSE) ]
    --oreganno  :   [ annotate SV regulatory element overlap (ORegAnno)(default FALSE) ]
    --tre       :   [ annotate SV tandem repeat overlap (VAMOS) (default FALSE) ]
    --mapflags  :   [ annotate SV with overlap of difficult to map regions (centromeres, telomeres, repeats,.. 
                                  ..segdups, gaps, homopolymers) (default FALSE) ]
    --hiconf    :   [ annotate SVs fully contained in high-confidence regions (default FALSE) ]

    """
}

bedHelp() {
    echo """
    Usage: needLR bed <options> {input}
    
    Required:

    positional parameters  : [ full path to input bed files ]
    
    Additional options:
    -L     : [ .txt file list of full file paths to query beds ]
    -O     : [ output directory name (default is needLR_output relative to current directory) ]

    """
}

############################# preprocessing and validation functions #######################################################################################

validateVCF () {
    local vcf=$1

    inputName="${vcf##*/}"
    inputExt="${inputName##*.}"

    if [[ ! -f $vcf ]]
    then
        echo "${bold}Error: ${normal}$vcf could not be located and may not exist"
        exit 1
    else
        if [[ $inputExt == "vcf" ]]
        then
            #attempt to bgzip and index
            bgzip $vcf
            tabix -p vcf $vcf.gz
            if [ -f "$vcf".gz.tbi ] || [ -f "$vcf.gz.csi" ]
            then
                echo "$vcf".gz
            else
                # quit if it can't be indexed
                echo "${bold}Error: ${normal}$vcf could not be zipped and indexed"
                echo ""
                ${subcommand}Help
                #exit 1
            fi
        elif [[ *"$vcf"* == *"vcf.gz"* ]]
        then
            if [ -f "$vcf".tbi ] || [ -f "$vcf.csi" ]
            then
                echo "$vcf" 
            else
                #if index not found, attempt to index
                tabix -p vcf "$vcf"
                if [ -f "$vcf".tbi ] || [ -f "$vcf.csi" ]
                then
                    echo "$vcf"
                else
                    # quit if it can't be indexed
                    echo "${bold}Error: ${normal}$vcf could not be indexed"
                    echo ""
                    ${subcommand}Help
                    #exit 1
                fi
            fi
        fi
    fi
}

truvari_ctrl_merge () {
    local ctrl_files=$1
    local output=$2
    local reorder=$3

    query_list=( $(echo ${ctrl_files} | tr ',' ' ') )

    echo -e "\nMerging Control Sets\n"
    #output="${UNSOLVED_DIR}/$(basename ${query_file} .vcf.gz).intermediate"

    #This preprocesses the control VCFs to be >=50bp, on full chromosomes, and FILTER=PASS
    echo "Preprocessing query VCF to SVs >=50bp, on full chromosomes, FILTER=$FILTERPASS"
    #bcffilters=\''(INFO/SVTYPE="BND") || (INFO/SVTYPE="INS" || INFO/SVTYPE="DEL" || INFO/SVTYPE="DUP" || INFO/SVTYPE="INV") && (INFO/SVLEN > 49 || INFO/SVLEN < -49) && GT!="0/0" && GT!="0|0"'\'
    chroms="chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrX,chrY,chrM"

    if [ -f "${temp}.list_temp.txt" ]
    then
        rm "${temp}.list_temp.txt"
    fi

    for((i=0;i<${#query_list[@]};i++))
    do
        query_file=${query_list[$i]}
        currentlines=$( zgrep -v ^# ${query_file} | wc -l | tr -s ' ' | cut -f1 -d ' ')
        echo "There are $currentlines starting variants in ${query_file}"

        
        if [ $FILTERPASS -eq 1 ]
        then
            bcftools view -f PASS \
            -i '(INFO/SVTYPE="BND") || (INFO/SVTYPE="INS" || INFO/SVTYPE="DEL" || INFO/SVTYPE="DUP" || INFO/SVTYPE="INV") && (INFO/SVLEN > 49 || INFO/SVLEN < -49) && GT!="0/0" && GT!="0|0"' \
                -r $chroms \
                -o ${output}.${i}.filter.vcf.gz \
                --threads ${THREADS} \
                --write-index=tbi "${query_file}"
        else
            bcftools view -i '(INFO/SVTYPE="BND") || (INFO/SVTYPE="INS" || INFO/SVTYPE="DEL" || INFO/SVTYPE="DUP" || INFO/SVTYPE="INV") && (INFO/SVLEN > 49 || INFO/SVLEN < -49) && GT!="0/0" && GT!="0|0"' \
                -r $chroms \
                -o ${output}.${i}.filter.vcf.gz \
                --threads ${THREADS} \
                --write-index=tbi "${query_file}"
        fi

        newlines=$( zgrep -v ^# ${output}.${i}.filter.vcf.gz | wc -l | tr -s ' ' | cut -f1 -d ' ')
        delta=$(( currentlines-newlines ))
        echo "Removed $delta lines from ${query_file}"
        currentlines=$newlines

        echo "${output}.${i}.filter.vcf.gz" >> "${temp}.list_temp.txt" #actually adding to the list inside of the loop
    done

    #This creates the input list of VCFs for bcftools merge
    echo "Creating list of input VCFs for bcftools merge"
    echo "${DATA1KG}" >> "${temp}.list_temp.txt"

    #bcftools merge
    echo "Merging"
    bcftools merge -m none \
        --force-samples \
        -l "${temp}.list_temp.txt" \
        -Oz \
        --threads $THREADS \
        -o "${output}_bcftools_merged_with_ctrl_temp.vcf.gz" \
        --write-index=tbi

    if [[ ${reorder}!="no_reorder" ]]
    then
        bcftools view --threads $THREADS \
        --force-samples \
        --samples-file ${reorder} \
        -O z \
        -o "${output}_bcftools_merged_with_ctrl_temp.ordered.vcf.gz" \
        --write-index=tbi \
        "${output}_bcftools_merged_with_ctrl_temp.vcf.gz"
    else
        mv "${output}_bcftools_merged_with_ctrl_temp.vcf.gz" "${output}_bcftools_merged_with_ctrl_temp.ordered.vcf.gz"
    fi

    newlines=$( zgrep -v ^# ${output}_bcftools_merged_with_ctrl_temp.ordered.vcf.gz | wc -l | tr -s ' ' | cut -f1 -d ' ')
    delta=$(( currentlines-newlines ))
    echo "Added $delta lines"
    currentlines=$newlines

    #Truvari collapse (T31)
    echo "Running truvari collapse"
    truvari collapse -i "${output}_bcftools_merged_with_ctrl_temp.ordered.vcf.gz" \
        -o "${output}_truvari_merged_temp.vcf" \
        -c "${output}_truvari_collapsed_temp.vcf" \
        -k "${truvari_k}" \
        -s "${truvari_s}" \
        -S "${truvari_S}" \
        -r "${truvari_r}" \
        -p "${truvari_p}" \
        -P "${truvari_P}" \
        -O "${truvari_O}"
    
    bcftools sort -O z -o "${output}.truvari_merged_controls.vcf.gz" --write-index=tbi "${output}_truvari_merged_temp.vcf" 

    echo -e "\nDone\n"
}


############################# input processing #######################################################################################
#### get subcommand to run

if [ "${#@}" -lt 1 ]
then
    help
    exit 1
fi



subcommand=$1

case ${subcommand} in
    annotate|bed|comparator) ;;
    help|?) help
            exit 0 ;;
    *version) echo "NeedLR version $version"
        exit 0 ;;
    *) echo -e "\nCommand $subcommand not recognized"
        help
        exit 1 ;;
esac

shift

alcannotations=""

### get other flags and options
while getopts HP:C:L:Q:O:B:T:R:S:-: option
do
    case "${option}" in
        -)
            longoption="${OPTARG}"
            case "${longoption}" in
                omim|gencc|hpo|pli|utr|cds|oreganno|tre|mapflags|hiconf)
                alcannotations+=$alcannotations,$longoption ;;

                all) SELECTEDANNO=$(echo ${ALLANNOTATIONLIST[@]} | tr ' ' ',') ;;
                keep1kg) MERGECONTROLS=1 ;;
                melt1kg) MELTCONTROLS=1 ;;
                *) echo "option $longoption not recognized, ignoring" ;;
            esac ;;
        H) help
           exit 0 ;;
        P) PARENTALVCFS="${OPTARG}" ;;
        C) TRUVARI_MERGED_CTRL_SET="${OPTARG}" ;;
        L) QUERY_VCFS="${OPTARG}" ;;
        Q) COHORT_VCF="${OPTARG}" ;;
        O) OUTPUTDIR="${OPTARG}" ;;
        B) refloc="${OPTARG}" ;;
        T) THREADS="${OPTARG}" ;;
        F) FILTERPASS=1 ;;
        R) ANALYSISREGION="${OPTARG}" ;;
        S) SUBPOPS="${OPTARG}" ;;
        
    esac
done

temp="${OUTPUTDIR}/needlr.temp"

if [[ ! -d ${OUTPUTDIR} ]]
then
    mkdir -p ${OUTPUTDIR}
fi

if [ ${#alcannotations} -gt 0 ]
then
    SELECTEDANNO=${alcannotations}
else
    SELECTEDANNO=$(echo ${ALLANNOTATIONLIST[@]} | tr ' ' ',')
fi

### get positional parameters

shift "$(($OPTIND -1))"

INPUTS=( "$@" )


#### process options and parameters

## check that input exists either as positional parameter, a list, or a vcf or a bed. don't fail the bed yet

# check positional first. if supplied this way, other options are ignored
INPUT_BEDS=()
INPUT_VCFS=()
numInputs="${#INPUTS[@]}"
echo ""
if [[ $numInputs -gt 0 ]]
then
    echo "found ${numInputs} positional arguments, ignoring input from -Q and -L"

    filetypes=()

    for vcf in ${INPUTS[@]}
    do
        inputName=${vcf##*/}
        inputExt=${inputName#*.}
        if [[ $inputExt == "bed" ]]
        then
            INPUT_BEDS+=( "$vcf" )
        elif [[ *"$inputExt"* == *"vcf"* ]]
        then
            INPUT_VCFS+=( $(validateVCF $vcf) )
        else
            echo "Error: File extension $inputExt not recognized, quitting"
            echo "You provided: $vcf"
            exit 1
        fi
    done
elif [[ -z "${QUERY_VCFS+x}" ]]
then
    if [[ -z "${COHORT_VCF+x}" ]]
    then
        echo "${bold}Error: ${normal}no input from -Q, -L, or positional parameters found"
        echo ""
        ${subcommand}Help
        exit 1
    else
    #this block validates the cohort vcf
    # it checks that it exists and ends in vcf.gz and has an index
        if [[ ! -f ${COHORT_VCF} ]]
        then
            echo "${bold}Error: ${normal}File ${COHORT_VCF} could not be found"
            echo ""
            ${subcommand}Help
            exit 1
        fi
        if [[ ! "${COHORT_VCF}" =~ "vcf.gz" ]]
        then
            echo "${bold}Error: ${normal}File ${COHORT_VCF} does not appear to be bgzipped"
            echo ""
            ${subcommand}Help
            exit 1
        fi
        if [[ ! -f "${COHORT_VCF}.tbi" ]] && [[ ! -f "${COHORT_VCF}.csi" ]]
        then
            echo "${bold}Error: ${normal}File ${COHORT_VCF} index not located"
            echo ""
            ${subcommand}Help
            exit 1
        fi
        # cohort_vcf is valid - assign it to the input list.
        INPUT_VCFS=( ${COHORT_VCF} )
    fi
else
    # this block validates the list of file input provided to query_vcfs
    # checks that it exists.
    if [[ ! -f ${QUERY_VCFS} ]]
    then
        echo "${bold}Error: ${normal}File ${QUERY_VCFS} could not be found"
        echo ""
        ${subcommand}Help
        exit 1
    fi
    QUERY_VCF_LIST=( $(cat ${QUERY_VCFS} ) )
    # check that the file is not empty
    if [[ ${#QUERY_VCF_LIST[@]} -lt 1 ]]
    then
        echo "${bold}Error: ${normal} ${QUERY_VCFS} is an empty file"
        echo ""
        ${subcommand}Help
        exit 1
    fi
    # query vcf is valid, iterate over it and check file type, adding valid vcf.gz and vcfs to a list
    for vcf in ${QUERY_VCF_LIST[@]}
    do
        inputName=${vcf##*/}
        inputExt=${inputName#*.}
        if [[ $inputExt == "bed" ]]
        then
            INPUT_BEDS+=( "$vcf" )
        elif [[ *"$inputExt"* == *"vcf"* ]]
        then
            INPUT_VCFS+=( $(validateVCF $vcf ) )
        fi
    done
fi


# check if using an external control set vcf
if [[ ! -z ${TRUVARI_MERGED_CTRL_SET+x} ]]
then
    run1kg=0
    CTRL_MERGED=${TRUVARI_MERGED_CTRL_SET}
    CTRL_SAMPLE_NAME_LIST=( $(bcftools view -h ${CTRL_MERGED} | grep -v ^## | cut -f10-) )
    TOTAL_SAMPLES=${#CTRL_SAMPLE_NAME_LIST[@]}

    # read from either a textfile or the comma and colon separated pairs 
    if [ ! -z ${SUBPOPS+x} ]
    then
        RUNSUBPOPS=1
        # check if $SUBPOPS is a file
        if [[ ${SUBPOPS} =~ "tsv" || ${SUBPOPS} =~ "csv" ]]
        then
            # read contents of file and then reset subpops and control vcf variables
            cat ${SUBPOPS} | tr ',' '\t' | sort -k2,2 > $temp.custom_ctrls_names.tsv
            cut -f1 $temp.custom_ctrls_names.tsv > $temp.subpop.ordered.names.txt
            labelnames=( $(cut -f2 $temp.custom_ctrls_names.tsv | uniq ) )
            cut -f2 $temp.custom_ctrls_names.tsv | awk '{subpops[$0]+=1}END{for(i in subpops){print i,subpops[i]}}' > $temp.subpop.unordered.counts.txt
            subpoplevels=()
            for label in ${labelnames[@]}
            do
                labelcount=$( grep $label $temp.subpop.unordered.counts.txt | cut -d ' ' -f2)
                subpoplevels+=( "${label}:${labelcount}" )
            done
            SUBPOPS=$(echo ${subpoplevels[@]} | tr ' ' ',')
            echo "sorting samples in control VCF by supopulation"
            bcftools view --threads ${THREADS} \
                --samples-file $temp.subpop.ordered.names.txt \
                --force-samples \
                -Oz -o $temp.custom_control.reordered.vcf.gz \
                --write-index=tbi \
                ${CTRL_MERGED}
            CTRL_MERGED=$temp.custom_control.reordered.vcf.gz
        else
            # subpop labels are supplied as pairs
            # get the names of custom control samples from the merged vcf
            # it is assummed that the samples are in order.
            CUSTOM_CTRL_SAMPLE_NAMES=( $(bcftools view -h ${CTRL_MERGED} | grep -v ^## | cut -f10-) )
            subgroups=( $(echo ${SUBPOPS} | tr ',' ' ') )
            offset=0
            echo "provided subgroups: ${subgroups}"
            
            if [ -f "$temp.custom_ctrls_names.tsv" ]
            then
                rm $temp.custom_ctrls_names.tsv
            fi
            for group in ${subgroups[@]}
            do
                grouplabels=( $(echo $group | tr ':' ' ') )
                label=${grouplabels[0]}
                labelcount=${grouplabels[1]}
                for((i=0;i<$labelcount;i++))
                do
                    sampleindex=$(($offset+$i))
                    echo -e "${CUSTOM_CTRL_SAMPLE_NAMES[$sampleindex]}\t${label}" >> $temp.custom_ctrls_names.tsv
                done
                offset=$(($offset+$labelcount))
            done
        fi
        #if SUBPOPS is not a file, make sure there are no repeats
        if [ ${MERGECONTROLS} -eq 0 ]
        then
            echo "Not merging controls with 1kg"
            # if not merging with 1kg controls, report counts for subgroups
            subgroups=( $(echo ${SUBPOPS} | tr ',' ' ') )
            SUBGROUP_LABELS=()
            SUBGROUP_COUNTS=()
            echo "Subpopulation counts are:"
            for group in ${subgroups[@]}
            do
                grouplabels=( $(echo $group | tr ':' ' ') )
                SUBGROUP_LABELS+=( ${grouplabels[0]} )
                SUBGROUP_COUNTS+=( ${grouplabels[1]} )
                echo "${grouplabels[0]}:${grouplabels[1]}"
            done
            NSUBGROUPS=${#SUBGROUP_LABELS[@]}
            uniquelabels=( $(echo ${SUBGROUP_LABELS[@]} | tr ' ' '\n' | sort | uniq ) )
            if [[ ${#uniquelabels[@]} -ne ${NSUBGROUPS} ]]
            then
                echo "Error: subgroups must be unique"
                echo "subgroups supplied: ${SUBGROUP_LABELS[@]}"
                exit 1
            fi
        else
            echo "merging provided controls with 1kg controls"
           # merge with the 1kg controls, optionally collapsing overlapping labels.
            LABELS_1KG=( AFR AMR EAS EUR SAS )
            SAMPLE_NAMES_1KG=( $(bcftools view -h ${DATA1KG} | grep -v ^## | cut -f10-) )
            if [ -f "$temp.1kg_ctrls_names.tsv" ]
            then
                rm $temp.1kg_ctrls_names.tsv
            fi
            for name in ${SAMPLE_NAMES_1KG[@]}
            do
                label=${name##*.} # use shell expansion to get the last '.' separated field with the population name
                if [[ ${MELTCONTROLS} -eq 0 ]]
                then
                    label="${label}_1KG"
                fi
                echo -e "${name}\t${label}" >> $temp.1kg_ctrls_names.tsv
            done

            cat $temp.custom_ctrls_names.tsv $temp.1kg_ctrls_names.tsv | sort -k2,2 > $temp.all_ctrls_names.sorted.tsv
            cut -f1 $temp.all_ctrls_names.sorted.tsv > $temp.all_ctrls_names.sorted.samples.txt
            ###########cut -f2 $temp.custom_ctrls_names.sorted.tsv > $temp.custom_ctrls_names.sorted.samples.txt
            ###DEBUG HERE
            # add the custom sample names and subgroups to the sample file
            cat $temp.all_ctrls_names.sorted.tsv

            truvari_ctrl_merge ${CTRL_MERGED} $temp.custom_control $temp.all_ctrls_names.sorted.samples.txt

            CTRL_MERGED=$temp.custom_control.truvari_merged_controls.vcf.gz
            CTRL_SAMPLE_NAME_LIST=( $(bcftools view -h ${CTRL_MERGED} | grep -v ^## | cut -f10-) )
            TOTAL_SAMPLES=${#CTRL_SAMPLE_NAME_LIST[@]}

            SUBGROUP_LABELS=( $(cut -f2 $temp.all_ctrls_names.sorted.tsv | uniq ) )
            SUBGROUP_COUNTS=()
            echo "Subpopulation counts are:"
            #for label in ${SUBGROUP_LABELS[@]}
            #do
            #    count=( $(cut -f2 $temp.all_ctrls_names.sorted.tsv | grep $label | wc -l | tr -s ' ' | cut -d ' ' -f1 ) )
            #    SUBGROUP_COUNTS+=( $count )
            #    echo "${label}:$count"
            #done
            labelstring=$(echo ${SUBGROUP_LABELS[@]} | tr ' ' ',' )
            SUBGROUP_COUNTS=( $( cat $temp.all_ctrls_names.sorted.tsv  | awk -F '\t' 'NR==1{subpop=$2;subcount=1}NR>1{if(subpop==$2){subcount+=1}else{print subcount;subcount=1;subpop=$2}}END{print subcount}' ) )
            for((i=0;i<${#SUBGROUP_COUNTS[@]};i++))
            do
                echo "${SUBGROUP_LABELS[$i]} : ${SUBGROUP_COUNTS[$i]}"
            done
            NSUBGROUPS=${#SUBGROUP_LABELS[@]}
        fi
    else
       NSUBGROUPS=0 
    fi
else
    #This is the Truvari merge of 500 1KGP samples
    CTRL_MERGED="${DATA1KG}"
    
    ##This is the list of the 1KGP sample names in the order they will be merged in Truvari
    CTRL_SAMPLE_NAME_LIST=( $(bcftools view -h ${CTRL_MERGED} | grep -v ^## | cut -f10-) )
    TOTAL_SAMPLES=${#CTRL_SAMPLE_NAME_LIST[@]}
    SUBGROUP_LABELS=( AFR AMR EAS EUR SAS )
    SUBGROUP_COUNTS=()
    echo "Subpopulation counts are:"
    for label in ${SUBGROUP_LABELS[@]}
    do
        count=$(echo ${CTRL_SAMPLE_NAME_LIST[@]} | tr ' ' '\n' | grep -c $label)
        SUBGROUP_COUNTS+=( $count )
        echo "${label}:$count (1kg built in)"
    done
    NSUBGROUPS=${#SUBGROUP_LABELS[@]}
    RUNSUBPOPS=1
fi

## add infocol text based on subgroups.
if [[ ${NSUBGROUPS} -gt 0 ]]
then
    for((i=0;i<${#SUBGROUP_LABELS[@]};i++))
    do
        subgroup=${SUBGROUP_LABELS[$i]}
        subcount=${SUBGROUP_COUNTS[$i]}
        INFOCOLTEXT["Pop_Count_${subgroup}"]='##INFO=<ID=Pop_Count_'"${subgroup}"',Number=1,Type=Integer,Description="Control '"${subgroup}"' samples carrying the SV (n='"${subcount}"')">'
        INFOCOLTEXT["Pop_Freq_${subgroup}"]='##INFO=<ID=Pop_Freq_'"${subgroup}"',Number=1,Type=Float,Description="Proportion of control '"${subgroup}"' samples carrying the SV">'
        INFOCOLTEXT["Allele_Count_${subgroup}"]='##INFO=<ID=Allele_Count_'"${subgroup}"',Number=1,Type=Integer,Description="Control '"${subgroup}"' alleles carrying the SV">'
        INFOCOLTEXT["Allele_Freq_${subgroup}"]='##INFO=<ID=Allele_Freq_'"${subgroup}"',Number=1,Type=Float,Description="Control '"${subgroup}"' sallele frequency">'
    done
fi


# from here options may only be necessary within each command.
# echo what options have already been processed

echo -e "\n${bold}needLR v4.0${normal}\n"
echo """Command         :   needLR $subcommand
        input VCFs      :   ${INPUT_VCFS[@]}
        input BEDs      :   ${INPUT_BEDS[@]}
        control vcf     :   ${CTRL_MERGED}
            # samples.  :   ${TOTAL_SAMPLES}
        output location :   ${OUTPUTDIR}
        analysis region :   ${ANALYSISREGION}

"""

############################# main functions #######################################################################################
############ core ##################



truvari_merge () {
    local query_files=$1
    local output=$2

    query_list=( $(echo ${query_files} | tr ',' ' ') )

    echo -e "\nStarting Step 1 (prep and merge)\n"
    #output="${UNSOLVED_DIR}/$(basename ${query_file} .vcf.gz).intermediate"

    #This preprocesses the query VCFs to be >=50bp, on full chromosomes, and FILTER=PASS
    echo "Preprocessing query VCF to SVs >=50bp, on full chromosomes, FILTER=$FILTERPASS"
    #bcffilters=\''(INFO/SVTYPE="BND") || (INFO/SVTYPE="INS" || INFO/SVTYPE="DEL" || INFO/SVTYPE="DUP" || INFO/SVTYPE="INV") && (INFO/SVLEN > 49 || INFO/SVLEN < -49) && GT!="0/0" && GT!="0|0"'\'
    chroms="chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrX,chrY,chrM"

    if [ -f "${temp}.list_temp.txt" ]
    then
        rm "${temp}.list_temp.txt"
    fi
    for((i=0;i<${#query_list[@]};i++))
    do
        query_file=${query_list[$i]}
        currentlines=$( zgrep -v ^# ${query_file} | wc -l | tr -s ' ' | cut -f1 -d ' ')
        echo "There are $currentlines starting variants in ${query_file}"

        
        if [ $FILTERPASS -eq 1 ]
        then
            bcftools view -f PASS \
            -i '(INFO/SVTYPE="BND") || (INFO/SVTYPE="INS" || INFO/SVTYPE="DEL" || INFO/SVTYPE="DUP" || INFO/SVTYPE="INV") && (INFO/SVLEN > 49 || INFO/SVLEN < -49) && GT!="0/0" && GT!="0|0"' \
                -r $chroms \
                -o ${output}.${i}.filter.vcf.gz \
                --threads ${THREADS} \
                --write-index=tbi "${query_file}"
        else
            bcftools view -i '(INFO/SVTYPE="BND") || (INFO/SVTYPE="INS" || INFO/SVTYPE="DEL" || INFO/SVTYPE="DUP" || INFO/SVTYPE="INV") && (INFO/SVLEN > 49 || INFO/SVLEN < -49) && GT!="0/0" && GT!="0|0"' \
                -r $chroms \
                -o ${output}.${i}.filter.vcf.gz \
                --threads ${THREADS} \
                --write-index=tbi "${query_file}"
        fi

        newlines=$( zgrep -v ^# ${output}.${i}.filter.vcf.gz | wc -l | tr -s ' ' | cut -f1 -d ' ')
        delta=$(( currentlines-newlines ))
        echo "Removed $delta lines from ${query_file}"
        currentlines=$newlines

        echo "${output}.${i}.filter.vcf.gz" >> "${temp}.list_temp.txt" #actually adding to the list inside of the loop
    done

    #This creates the input list of VCFs for bcftools merge
    echo "Creating list of input VCFs for bcftools merge"
    echo "${CTRL_MERGED}" >> "${temp}.list_temp.txt"

    #bcftools merge
    echo "Merging"
    bcftools merge -m none \
        --force-samples \
        -l "${temp}.list_temp.txt" \
        -Oz \
        --threads $THREADS \
        -o "${output}_bcftools_merged_with_ctrl_temp.vcf.gz" \
        --write-index=tbi

    newlines=$( zgrep -v ^# ${output}_bcftools_merged_with_ctrl_temp.vcf.gz | wc -l | tr -s ' ' | cut -f1 -d ' ')
    delta=$(( currentlines-newlines ))
    echo "Added $delta lines"
    currentlines=$newlines

    #Truvari collapse (T31)
    echo "Running truvari collapse"
    truvari collapse -i "${output}_bcftools_merged_with_ctrl_temp.vcf.gz" \
        -o "${output}_truvari_merged_temp.vcf" \
        -c "${output}_truvari_collapsed_temp.vcf" \
        -k "${truvari_k}" \
        -s "${truvari_s}" \
        -S "${truvari_S}" \
        -r "${truvari_r}" \
        -p "${truvari_p}" \
        -P "${truvari_P}" \
        -O "${truvari_O}"

    ##This parses the Truvari VCF output for relevant information
    echo "Parsing Truvari VCF output"
    bcftools query -f '%CHROM\t%POS\t%REF\t%ALT\t%INFO/SVLEN\t%INFO/SVTYPE[\t%GT\t%DV\t%DR]\n' \
        "${output}_truvari_merged_temp.vcf" > "${output}_truvari_merged_temp.txt"

    newlines=$( wc -l ${output}_truvari_merged_temp.txt | tr -s ' ' | cut -f1 -d ' ')
    echo "Truvari output has $newlines lines"

    echo -e "\nDone with Step 1\n"
}

parse_vcf() {
    local input=$1
    local output=$2
    local nquery=$3

    echo -e "Starting Step 2 (filter vcf)\n"

    currentlines=$( wc -l $input | tr -s ' ' | cut -f1 -d ' ')
    echo "There are $currentlines starting variants"

    echo "Filtering reference only calls"
    if [[ $nquery -gt 1 ]]
    then
        QUERY_LAST_GT=$(( 7 + ($nquery)*3 ))

        cat $input | awk -v first=7 \
        -v last="${QUERY_LAST_GT}" \
        -v step=3 'BEGIN {OFS="\t"}{
        for (i = first; i <= last; i += step) {
            if ($i != "./.") { print; next }
            }
        }' > "${output}_truvari_merged_query_filtered_temp.txt"
    else
        QUERY_GT=7
        cat $input | awk -v qcol=${QUERY_GT} \
        'BEGIN{OFS="\t"}{if($qcol!="./."){print $0}}' > "${output}_truvari_merged_query_filtered_temp.txt"
    fi
    newlines=$( wc -l "${output}_truvari_merged_query_filtered_temp.txt" | tr -s ' ' | cut -f1 -d ' ')
    delta=$(( currentlines-newlines ))
    echo "Removed $delta lines"
    currentlines=$newlines

    ##This removes BNDs from the analysis (too large to efficiently annotate)
    echo "Filtering BNDs"
    cat "${output}_truvari_merged_query_filtered_temp.txt" | grep -v BND > "${output}_temp1.txt"
    
    newlines=$( wc -l "${output}_temp1.txt" | tr -s ' ' | cut -f1 -d ' ')
    ldelta=$(( currentlines-newlines ))
    echo "Removed $delta lines"
    currentlines=$newlines

    ##This parses for SVs <=10Mb
    echo "Parsing for SVs <= 10Mb"
    cat "${output}_temp1.txt" | awk '{if($5 > -10000000 && $5 < 10000000){print $0}}' > \
        "${output}_temp2.txt"

    newlines=$( wc -l "${output}_temp2.txt" | tr -s ' ' | cut -f1 -d ' ' )
    delta=$(( currentlines-newlines ))

    echo "Removed $delta lines"
    currentlines=$newlines

    echo "There are $currentlines variants"

    # final output for this function is "${output}_temp2.txt"
    echo -e "\nDone with Step 2\n"
}    

collapse_gt() {
    local input=$1
    local output=$2
    local nquery=$3
    local keepDVDR=$4

    ##   Collapse to GT-only columns (drop DV/DR)
    ##   input layout (1-indexed):
    ##   $1-$6                  : CHROM POS REF ALT SVLEN SVTYPE
    ##   $7 .. $6+COHORT        : cohort GTs (one col per sample)
    ##   $7+COHORT .. $6+COHORT+CTRL : 1KGP GTs (one col per sample)
    ## this step also adds a '.' in position 3 to later hold the SV end pos
    echo -e "\nStarting Step 3 (preprocess gt columns)\n"

    STEP=3
    if [[ "${keepDVDR}" -eq 1 ]]
    then
        echo "keeping dv/dr"
        cat "${input}" | \
        awk -f $scriptpath/src/rearrange.awk \
         -v step=$STEP \
         -v ncohort=$nquery \
         -v ncontrols="${TOTAL_SAMPLES}" \
         | tr -s '\t' > "${output}_temp3.txt"
    else
        echo "keeping only gt columns"
        QUERY_END=$(( 7 + (nquery-1)  * 3 ))
        cat "${input}" | \
        awk -f $scriptpath/src/rearrange_dropdvdr.awk \
         -v step="${STEP}" \
         -v ncohort=$nquery \
         -v ncontrols="${TOTAL_SAMPLES}" \
         | tr -s '\t' > "${output}_temp3.txt"
    fi
    # final output for this function is "${output}_temp3.txt"
    echo -e "\nDone with Step 3\n"
}

make_supp_vecc() {
    local input=$1
    local output=$2
    local nquery=$3
    local keepDVDR=$4

    echo -e "\nStarting Step 4 (making support vector)\n"

    if [[ "${keepDVDR}" -eq 1 ]]
    then
        querycols=4
        echo "not dropping any query columns"
    else
        querycols=1
        echo "dropping query DV/DR columns"
    fi
    ##This creates a SUPP_VEC (like in Jasmine)
    Q_GT_START=8
    Q_GT_END=$(( 7 + (nquery*querycols) )) #preserving the closed interval
    Q_GT_STEP="${querycols}"
    CONTROL_GT_START=$(( Q_GT_END + 1 ))
    CONTROL_GT_END=$(( CONTROL_GT_START + TOTAL_SAMPLES - 1 )) #preserving the closed interval
    

    #If there is more than one sample, make a supp vecc for the cohort
    if [[ "${nquery}" -gt 1 ]]
    then
        echo "creating support vector for query cohort"
        cat "${input}" | awk -f $scriptpath/src/supvec.awk \
            -v start="${Q_GT_START}" \
            -v end="${Q_GT_END}" \
            -v step="${Q_GT_STEP}" | 
            awk 'BEGIN{OFS="\t"}{printf("%s\t\n", $0)}'> "${output}_temp4.1.txt"
    else
        cat "${input}" > "${output}_temp4.1.txt"
    fi

    # Always make one for controls
    echo "creating support vector for controls"
    cat "${output}_temp4.1.txt" | awk -f $scriptpath/src/supvec.awk \
        -v start="${CONTROL_GT_START}" \
        -v end="${CONTROL_GT_END}" \
        -v step=1 > "${output}_temp4.txt"

    ##Rearrange columns so SUPP_VECs are columns 8/9
    endcol=$( head -n1 ${output}_temp4.txt | awk '{print NF}' )
    let endcol=$endcol-1
    SUPP_VEC=$( cat "${output}_temp4.txt" | awk 'NR==1{print NF}' )
    if [[ "${nquery}" -gt 1 ]]
    then
        let SUPP_VEC="${SUPP_VEC}"-1
        let endcol=$endcol-1
    fi

    #SUPP_VEC=$(( CONTROL_GT_END + 1 )) # the position of the first support vector

    echo "Moving support vector(s)"
    paste <( cut -f 1-7 "${output}_temp4.txt" ) \
        <( cut -f "${SUPP_VEC}-" "${output}_temp4.txt" ) \
        <( cut -f "8-${endcol}" "${output}_temp4.txt" ) > "${output}_temp5.txt"


    ## Calculate population stratified frequency statistics
    ## this version of the awk script can accept any breaks, not implemented yet for anything but 1kg
    if [[ $RUNSUBPOPS -eq 1 ]]
    then
        subpopcounts=$(echo ${SUBGROUP_COUNTS[@]} | tr ' ' ',')
        echo "using subpopulation breaks: $subpopcounts"
    else
        subpopcounts="${TOTAL_SAMPLES}"
        echo "no subpopulation breaks provided"
    fi

    echo "calculating population stratified frequency statistics"
    cat "${output}_temp5.txt" | awk -f $scriptpath/src/annocustomcontrol.awk \
        -v controlbreaks=$subpopcounts \
        -v ncohort=$nquery \
        -v ncontrols="${TOTAL_SAMPLES}" \
        -v step=$querycols > "${output}_temp6.txt"


    ##This matches the SUPP_VEC string(s) to the sample list (and lists which 1KGP samples have the SV)
    
    names=$(echo "${CTRL_SAMPLE_NAME_LIST[@]}" | tr ' ' ',')
    if [[ $nquery -gt 1 ]]
    then
        echo "Matching vector support with cohort sample names"
        cohortnames=$(echo "${COHORT_SAMPLE_NAME_LIST[@]}" | tr ' ' ',')
        cat "${output}_temp6.txt" | \
            awk -f $scriptpath/src/matchSuppVecc.awk \
            -v names=$cohortnames \
            -v colindex=8 > "${output}_temp6.1.txt"
        echo "Matching vector support with control sample names"
        cat "${output}_temp6.1.txt" | \
            awk -f $scriptpath/src/matchSuppVecc.awk \
            -v names=$names \
            -v colindex=9 > "${output}_temp7.txt"
    else
        echo "Matching vector support with control sample names"
        cat "${output}_temp6.txt" | \
            awk -f $scriptpath/src/matchSuppVecc.awk \
            -v names=$names \
            -v colindex=8 > "${output}_temp7.txt"
    fi
    # final output for this function is ${output}_temp7.txt
    echo -e "\nDone with Step 4\n"
}

hwe() {
    local input=$1
    local output=$2
    local nquery=$3
    local keepDVDR=$4

    echo -e "\nStarting Step 5 (HWE)\n"
    if [[ "${keepDVDR}" -eq 1 ]]
    then
        querycols=4
    else
        querycols=1
    fi

    ## This calculates p for HWE - WT alle freq ((2*homWT) + het)/(2* (homWT + het + homVar))
    ## Checks for demoninator of zero (if SV is counted but genotype is ./. for a control sample)
    ## This calculates q for HWE - (1-p)
    ## This calculates np^2, 2npq, and nq^2 for HWE
    ## This calculates chi-squared value for HWE. (Can't divide by zero, so if expected is zero, chi-sq=NULL) 
    ## For efficiency what was previously seaprated into the steps above was combined into one awk script. 
    ## file output names preserved for readability
    echo "calculating HWE statistics"
    cat "${output}_temp7.txt" | \
        awk -f $scriptpath/src/hwe.awk \
        -v totsamples="${TOTAL_SAMPLES}" > "${output}_temp11.txt"

    #This lists all population counts/frequencies, allele counts/frequencies, and HWE info
    echo "Tabulating subpopulation and population count/frequencies"
    if [[ "${RUNSUBPOPS}" -eq 1 ]]
    then
        subpopcounts=$(echo ${SUBGROUP_COUNTS[@]} | tr ' ' ',')
    else
        subpopcounts="${TOTAL_SAMPLES}"
    fi
    cat "${output}_temp11.txt" | \
        awk -f $scriptpath/src/assign_counts.awk \
        -v ncontrols="${TOTAL_SAMPLES}" \
        -v ncohort="$nquery" \
        -v step=$querycols \
        -v controlcounts="${subpopcounts}" > "${output}_temp12.txt"

    echo "Assigning HWE equilibrium"
    #This determines if the SV is in HWE
    hwecol=$( awk 'NR==1{print NF-3}' "${output}_temp12.txt" )

    cat "${output}_temp12.txt" | \
        awk -f $scriptpath/src/hwe_check.awk | \
        cut -f 1-"${hwecol}" > "${output}_temp13.txt"

    echo "Assigning SV end position"
    ##This adds the absolute value of the length of the SV to the start position (DELs are listed as negative lengths in the vcf, but the range is from the start position plus that number of nucleotides)
    cat "${output}_temp13.txt" | \
        awk -f $scriptpath/src/svlen.awk > "${output}_control_overlap.txt"

    # final output for this funciton is ${output}_control_overlap.txt
    echo -e "\nDone with Step 5\n"
}

condenseSummary() {
    # this makes the summary for the cohort and drops GT control columns
    local input=$1
    local output=$2
    local nquery=$3
    local keepDVDR=$4

    echo -e "\nStarting Step 6 (summarizing and cleanup)\n"

    if [[ "${keepDVDR}" -eq 1 ]]
    then
        querycols=4
    else
        querycols=1
    fi

    ngts=${TOTAL_SAMPLES}
    samplecols=4
    if [[ $nquery -gt 1 ]]
    then
        let ngts+=$nquery
        let samplecols=1
    fi
     #offset for use with cut
    let keepend=8+$samplecols
    let loseend=$keepend+$ngts+1

    paste <(cut -f1-$keepend $input) \
        <(cut -f $loseend- $input) > "${output}_summarized.txt"

    echo -e "\nDone with Step 6\n"
    
}

inheritanceSupVec() {
    # this transforms the cohort support vector into a parental inheritnace column
    # it also notes records that are not present in the proband
    local input=$1
    local output=$2
    local nquery=$3
    local keepDVDR=$4

    # the cohort (parental) support vector will always be field 8
    if [[ $nquery == 3 ]]
    then
        cut -f8 $input | awk -F '_' '{if(NF==1 ){\
            if($0=="Proband"){print "de_novo"}
            else{print "not_present"}
        };\
        if(NF==3){print "inherited"};
        if(NF==2){\
            if($0!~/Proband/){
                print "not_present"}
            else if($0~/Maternal/){\
                print "maternal"}
            else if($0~/Paternal/){\
                print "paternal"}
            else {print "inherited"}}}' > $output.inheritances.txt
    else
        cut -f8 $input | awk -F '_' '{if($0!~/Proband/){print "not_present"}\
        else if(NF==1 && $0=="Proband"){print "not_inherited"}\
        else if(NF==2){print "inherited"}}' > $output.inheritances.txt
    fi

    paste <(cut -f1-7 ${input}) $output.inheritances.txt <(cut -f9- ${input})  > ${output}_inheritance.txt 
}

cohortControlOverlap() {
    local query=$1
    local output=$2

    # get number of samples and sample names from the input
    COHORT_SAMPLE_NAME_LIST=( $(bcftools view -h ${query} | grep -v ^## | cut -f10-) )
    COHORT_SAMPLES=${#COHORT_SAMPLE_NAME_LIST[@]}

    truvari_merge "${query}" "${output}"
    parse_vcf "${output}_truvari_merged_temp.txt" "${output}" "${COHORT_SAMPLES}"
    collapse_gt "${output}_temp2.txt" "${output}" "${COHORT_SAMPLES}" 0
    make_supp_vecc "${output}_temp3.txt" "${output}" "${COHORT_SAMPLES}" 0
    hwe "${output}_temp7.txt" "${output}" "${COHORT_SAMPLES}" 0
    condenseSummary "${output}_control_overlap.txt" "${output}" "${COHORT_SAMPLES}" 0

}


singleVCFControlOverlap() {
    local query=$1
    local output=$2

    truvari_merge "${query}" "${output}"
    parse_vcf "${output}_truvari_merged_temp.txt" "${output}" 1
    collapse_gt "${output}_temp2.txt" "${output}" 1 1
    make_supp_vecc "${output}_temp3.txt" "${output}" 1 1
    hwe "${output}_temp7.txt" "${output}" 1 1
    condenseSummary "${output}_control_overlap.txt" "${output}" 1 1

}

multiVCFControlOverlap() {
    local queries=$1
    local output=$2
    local n=$3

    truvari_merge "${queries}" "${output}"
    parse_vcf "${output}_truvari_merged_temp.txt" "${output}" ${n}
    collapse_gt "${output}_temp2.txt" "${output}" ${n} 0 #read depth columns are dropped here
    # keep gt,alt depth,ref depth for later
    let ncols=3*n
    let colend=$ncols+6
    let cutcol=4*n

    cut -f7-${colend} ${output}_temp2.txt | awk 'BEGIN{OFS="\t"}\
        {for(i=1;i<=NF;i+=3){\
            totalreads=$(i+1)+$(i+2);\
            if(totalreads==""){totalreads="."}
            printf("%s\t%s\t%s\t%s\t", $i,$(i+1),$(i+2),totalreads)}
        printf "dummy\n"}' | \
        cut -f1-${cutcol} > ${output}_dvdr.txt
    make_supp_vecc "${output}_temp3.txt" "${output}" ${n} 0
    hwe "${output}_temp7.txt" "${output}" ${n} 0
    condenseSummary "${output}_control_overlap.txt" "${output}" ${n} 0
    inheritanceSupVec ${output}_summarized.txt ${output} ${n} 0
}

annotateGenes() {
    #This annotates each variant with gene info (+/-5kb to try to capture promoters, etc)
    local input=$1
    local output=$2

    NF=$(head -n1 $input | awk '{print NF}')
    let geneFieldInitial=$NF+4
    let geneField=$NF+1


    echo -e "\nAnnotating gene overlap\n"

    # remove gene coordinates from output and sort on gene name
    # previously output_temp18.txt
    bedtools intersect -wa -wb -loj \
        -a $input \
        -b $GENES | cut -f1-${NF},${geneFieldInitial} | sort -k${geneField},${geneField} > "${output}_genes.txt"

    echo -e "\nDone\n"
}

geneIndexedAnnotations() {
    local input=$1
    local output=$2
    local geneField=$3
    local indexField=$4

    # apply name indexed annotations
    echo "Assigning name indexed annotations"

    if [[ "${SELECTEDANNO}" =~ "omim" ]]
    then
        #adds two columns
        echo "Applying OMIM annotations"
        bash $scriptpath/src/annotateNamed.sh -i ${input} -o ${output}_omim.txt -a ${OMIM_GENES} -c 1,3 -g $geneField
        input=${output}_omim.txt
    fi
    if [[ "${SELECTEDANNO}" =~ "gencc" ]]
    then
        #adds three columns
        echo "Applying GENCC annotations"
        bash $scriptpath/src/annotateNamed.sh -i ${input} -o ${output}_gencc.txt -a ${GENCC} -g $geneField
        input=${output}_gencc.txt
    fi
    if [[ "${SELECTEDANNO}" =~ "hpo" ]]
    then
        #adds one column
        echo "Applying HPO term annotations"
        bash $scriptpath/src/annotateNamed.sh -i ${input} -o ${output}_hpo.txt -a "${OMIM_GENES}" -c 4 -g $geneField
        input=${output}_hpo.txt
    fi
    if [[ "${SELECTEDANNO}" =~ "pli" ]]
    then
        #adds one column
        echo "Applying gnomAD pLI annotations"
        bash $scriptpath/src/annotateNamed.sh -i ${input} -o ${output}_pli.txt -a ${PLI} -g $geneField
        input=${output}_pli.txt
    fi

    # Consolidate multigene rows
    echo "Consolidating multigene rows"
    cat $input | awk -f $scriptpath/src/consolidateRows.awk \
        -v indexField=$indexField > ${output}_consolidated.txt
    

    ##Replace empty fields with "."
    awk 'BEGIN {FS = OFS = "\t"} {for (i = 1; i <= NF; i++) if ($i == "") $i = "."} 1' ${output}_consolidated.txt > ${output}_filled.txt

    echo "Name indexed annotations complete"
}

positionIndexedAnnotations() {
    local originalInput=$1
    local output=$2

    echo "Assigning position based annotations"
    bedtools sort -i $originalInput > "${output}"_pos_sorted.txt
    input="${output}"_pos_sorted.txt
    if [[ "${SELECTEDANNO}" =~ utr ]]
    then
        echo "Finding UTR overlap"
        bedtools map \
        -a "$input" \
        -b "$UTR" \
        -c 5 \
        -o distinct \
        > "${output}"_utr.txt
        input=${output}_utr.txt
    fi
    if [[ "${SELECTEDANNO}" =~ cds ]]
    then
        echo "Finding CDS overlap"
        bedtools map \
        -a "${input}" \
        -b "$CDS" \
        -c 6 \
        -o collapse \
        | awk 'BEGIN{FS=OFS="\t"} \
        {$NF= ($NF==-1 || $NF==".") ? "." : "CDS" ; print $0}' > "${output}"_cds.txt
        input=${output}_cds.txt
    fi
    if [[ "${SELECTEDANNO}" =~ oreganno ]]
    then
        echo "Finding OregaNNO overlap"
        bedtools map \
        -a "$input" \
        -b "$OREGANNO" \
        -c 4 \
        -o distinct \
        > "${output}"_oreganno.txt
        input=${output}_oreganno.txt
    fi
    if [[ "${SELECTEDANNO}" =~ tre ]]
    then
        echo "Finding TRE overlap"
        awk 'BEGIN{FS=OFS="\t"} $7!="INS" && $7!="DEL" && $7!="DUP" {print $0, "."}' \
            "${input}" > "${output}"_novamos.txt
        bedtools map \
            -a ${input} \
            -b $VAMOSEXPAND \
            -c 4 \
            -o distinct | \
            awk -F '\t' '{if($7=="DUP" || $7=="INS"){print $0}}' > ${output}_insdup.txt
        bedtools map \
            -a ${input} \
            -b $VAMOS \
            -c 4 \
            -o distinct | \
            awk -F '\t' '{if($7=="DEL"){print $0}}' > ${output}_del.txt
        cat ${output}_insdup.txt ${output}_del.txt ${output}_novamos.txt | \
            awk 'BEGIN{FS=OFS="\t"} {$NF=($NF==-1||$NF==".")?".":"vamos"; print}' \
            | sort -k1,1 -k2,2n -k3,3n | uniq > ${output}_tre.txt
        input=${output}_tre.txt
    fi
    if [[ "${SELECTEDANNO}" =~ mapflags ]] #includes centromeres, pericentromeres, telomeres, segdups, repeats, gaps, homopolymers
    then
        # centromeres, pericentromeres, telomeres
        echo "Finding centromeres, pericentromere, telomere overlap"
        NF=$( head -n1 ${input} | awk -F '\t' '{print NF}')
        let offset=$NF+4
        let newNF=$NF+6
        bedtools intersect -wa -wb -loj \
            -a ${input} \
            -b ${HG38_REGIONS} \
            | cut -f1-$NF,$offset-$newNF > ${output}_meres.txt
        input=${output}_meres.txt

        echo "Finding segdup overlap"
        bedtools map \
            -a ${input} \
            -b ${SEGDUPS} \
            -c 4 \
            -o distinct > ${output}_segdups.txt
        input=${output}_segdups.txt
        
        echo "Finding short repeat overlap"
        bedtools map \
            -a ${input} \
            -b ${REPEAT_MASKER} \
            -c 6 \
            -o distinct | awk 'BEGIN{FS=OFS="\t"} {$NF=($NF==-1||$NF==".")?".":"repeat"; print}' > \
            ${output}_repeats.txt
        input=${output}_repeats.txt

        echo "Finding reference gap overlap"
        bedtools map \
            -a ${input} \
            -b ${GAPS} \
            -c 4 \
            -o distinct > ${output}_gaps.txt
        input=${output}_gaps.txt

        echo "Finding homopolymer >= 50bp overlap"
        bedtools map \
            -a ${input} \
            -b ${HOMOPOLYMERS} \
            -c 4 \
            -F 1.0 \
            -o distinct | \
            awk 'BEGIN{FS=OFS="\t"} {$NF=($NF==-1||$NF==".")?".":"HP>=50bp"; print}' \
            > ${output}_homopolymers.txt
        input=${output}_homopolymers.txt

    fi
    if [[ "${SELECTEDANNO}" =~ hiconf ]]
    then
        echo "Finding high confidence region overlap"
        bedtools map \
            -a ${input} \
            -b ${DEFRABB_HICONF} \
            -c 4 \
            -o distinct > ${output}_hiconf.txt
        input=${output}_hiconf.txt
    fi

    cp $input ${output}_posannotations.txt
    echo "Position based annotations complete"
}


printVCF() {
    local vcf=$1
    local input=$2
    local output=$3
    local finalOutput=$4
    local n=$5

    qid=$(basename "$vcf" .vcf.gz)

    echo "Building output VCF"

    paste <( cat $input | awk -v qid=$qid 'BEGIN{OFS="\t"}\
    NR==1{print $1,$2,$4,$5,$6,$7,$3,"Query_ID"}\
    NR>1{print $1,$2,$4,$5,$6,$7,$3,qid}' ) <(cut -f8- $input ) > ${output}_vcf_rearrange.txt

    # infolines built on the input table header
    tableheader=( $(head -n1 ${output}_vcf_rearrange.txt | cut -f 5- ) )
    echo ${tableheader[@]}

    # pull file format and contig list from input vcf for future compatability with different references
    zgrep ^##fileformat $vcf > ${output}.vcf
    zgrep ^##contig= $vcf >> ${output}.vcf

    infolines=()
    for field in ${tableheader[@]}
    do
        echo $field
        infolines+=( ${INFOCOLTEXT[$field]} )
    done

    echo ${infolines[@]} | sed 's/##/\n##/g' | tail -n+2 >> ${output}.vcf

    echo -e '#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO' >> ${output}.vcf
    # in a future version should output format tag from original VCF when running just one sample

    infoheaderval=$( echo ${tableheader[@]} | tr ' ' '|' )

    tail -n+2 ${output}_vcf_rearrange.txt | \
        sed 's/;/,/g' | \
        awk -F '\t' \
            -v header=${infoheaderval} \
            'BEGIN{OFS="\t"; ninfo=split(header,infoarray,"|")}
            {
                printf("%s\t%s\t%s\t%s\t%s\t%s\t%s\t",$1,$2,".",$3,$4,".",".")
                for(i=5;i<=NF;i++)
                {
                    printf("%s=%s;", infoarray[i-4], $i)
                }
                printf("\n")
            }' >> ${output}.vcf

    bcftools sort ${output}.vcf -O z -o ${finalOutput}.vcf.gz --write-index=tbi

}


printAnnotationHeader() {
    annotationcols=0
    tableheader=()
    if [[ "${SELECTEDANNO}" =~ "omim" ]]
    then
        tableheader+=( OMIM_phenotype OMIM_MOI )
        let annotationcols+=2
    fi
    if [[ "${SELECTEDANNO}" =~ "gencc" ]]
    then
        tableheader+=( GENCC_phenotype GENCC_support GENCC_MOI )
        let annotationcols+=3
    fi
    if [[ "${SELECTEDANNO}" =~ "hpo" ]]
    then
        tableheader+=( HPO_terms )
        let annotationcols+=1
    fi
    if [[ "${SELECTEDANNO}" =~ "pli" ]]
    then
        tableheader+=( pLI )
        let annotationcols+=1
    fi
    if [[ "${SELECTEDANNO}" =~ "utr" ]]
    then
        tableheader+=( UTR )
        let annotationcols+=1
    fi
    if [[ "${SELECTEDANNO}" =~ "cds" ]]
    then
        tableheader+=( CDS )
        let annotationcols+=1
    fi
    if [[ "${SELECTEDANNO}" =~ "oreganno" ]]
    then
        tableheader+=( ORegAnno )
        let annotationcols+=1
    fi
    if [[ "${SELECTEDANNO}" =~ "tre" ]]
    then
        tableheader+=( TRE )
        let annotationcols+=1
    fi
    if [[ "${SELECTEDANNO}" =~ "mapflags" ]]
    then
        tableheader+=( Centromeric Pericentromeric Telomeric Segdup Repeat Gap Homopolymer )
        let annotationcols+=7
    fi
    if [[ "${SELECTEDANNO}" =~ "hiconf" ]]
    then
        tableheader+=( HiConf )
        let annotationcols+=1
    fi

    echo "$annotationcols" "${tableheader[@]}"
}

printTable() {
    local input=$1
    local output=$2
    local finalOutput=$3
    local nquery=$4

    echo "Printing tabular results to ${finalOutput}_RESULTS.tsv"

    # make different headers depending on input options
    tableheader=( CHROM POS End_Pos REF ALT SVLEN SVTYPE )
    case $nquery in
        1) tableheader+=( Control_support Genotype Alt_Reads Ref_Reads Total_Reads ) ;;
        2) tableheader+=( Inheritance Control_support Genotype Alt_Reads Ref_Reads Total_Reads Parental_GT Parental_Alt_Reads Parental_Ref_Reads Parental_Total_Reads) ;;
        3) tableheader+=( Inheritance Control_support Genotype Alt_Reads Ref_Reads Total_Reads Maternal_GT Maternal_Alt_Reads Maternal_Ref_Reads Maternal_Total_Reads Paternal_GT Paternal_Alt_Reads Paternal_Ref_Reads Paternal_Total_Reads ) ;;
        *) tableheader+=( Cohort_support Control_support Pop_Count_Cohort Pop_Freq_Cohort Allele_Count_Cohort Allele_Freq_Cohort GT_coh_homWT GT_coh_het GT_coh_homVAR )
    esac

    sampleend=${#tableheader[@]}
    
    
    annotationcols=1
    tableheader+=( Allele_Freq_ALL_Control Genes )
    annocols=( $(printAnnotationHeader) )
    let annotationcols+=${annocols[0]}
    tableheader+=( ${annocols[@]:1} )

    let controlstart=$sampleend+1
    let controlend=controlstart
    if [[ $NSUBGROUPS -gt 1 ]] #this should be replaced with optional subpopulation names in a later release
    then
        poplabels=()
        allelelabels=()
        for subgroup in ${SUBGROUP_LABELS[@]}
        do
            poplabels+=( "Pop_Count_${subgroup}" "Pop_Freq_${subgroup}")
            allelelabels+=( "Allele_Count_${subgroup}" "Allele_Freq_${subgroup}")
        done
        tableheader+=(  ${poplabels[@]}
                        Pop_Count_ALL Pop_Freq_ALL 
                        ${allelelabels[@]}
                        Allele_Count_ALL Allele_Freq_ALL )

        let controlend=$controlstart+${#poplabels[@]}+${#allelelabels[@]}+3
        afcol=$controlend
    else
        echo "no subgroups"
        tableheader+=( Pop_Count_ALL Pop_Freq_ALL Allele_Count_ALL Allele_Freq_ALL )
        let controlend=$controlstart+3
        afcol=$controlend
    fi

    tableheader+=( GT_homWT GT_het GT_homVAR p q HWE  )
    let gtstart=$controlend-1
    let gtstop=$controlend+6

    let annostart=$gtstop+1

    if [[ ! -z ${COHORT_VCF+x} ]]
    then
        paste <(cat $input | cut -f 1-$sampleend,$afcol,${annostart}- ) \
            <(cat $input | cut -f $controlstart-${gtstop} ) > ${output}_results_long.txt
    else
        paste <(cat $input | cut -f 1-$sampleend,$afcol,${annostart}- ) \
            <(cat $input | cut -f $controlstart-${gtstop} ) > ${output}_results_long.txt
    fi

    ## truncate oversized fields, write header, filter result files

    longcols=( 4 5 ) #REF ALT
    let annotationstart=$sampleend+2
    NF=$( head -n1 ${output}_results_long.txt | awk '{print NF}' )
    SUBGROUPCOLUMNS=$(( ${NSUBGROUPS}*4 ))
    let annotationstop=$NF-6-$SUBGROUPCOLUMNS
    echo "annotationstop: $annotationstop"
    
    echo "${tableheader[@]}" | tr ' ' '\t' > ${finalOutput}_RESULTS.tsv
        
    cat ${output}_results_long.txt | \
        awk -F '\t' -v annostart=${annotationstart} -v annostop=${annotationstop} \
        -v ref=4 -v alt=5 'BEGIN{OFS="\t"}\
        {if(length($ref) > 30000){$ref="[too_long_see_vcf]"};
            if(length($alt) > 30000){$alt="[too_long_see_vcf]"};
            for(i=annostart;i<=annostop;i++){
                if(length($i) > 30000){$i="[too_long_see_vcf]"}};
            print $0}' >> ${finalOutput}_RESULTS.tsv
    
    #This removes "?s" from OMIM annotations (hard to sort)
    sed -i 's/?//g' ${finalOutput}_RESULTS.tsv
    #This removes empty lines from the bottom of the txt file
    sed -i -e :a -e '/^[[:space:]]*$/{$d;N;ba}' ${finalOutput}_RESULTS.tsv
}

filterTable() {
    local input=$1
    local output=$2

    if [ -z ${COHORT_VCF+x} ] #if running with a cohort, account for different # cols
    then
        afcol=13
    else
        afcol=17
    fi

    ##Filtered output 1: SVs absent from 1KGP entirely (afcol = Allele_Freq_ALL_1KGP)
    awk -F'\t' -v afcol=$afcol 'BEGIN{OFS="\t"} NR==1 || $afcol==0 {print}' \
     $input > "${output}_RESULTS_unique.tsv"

    ##Filtered output 2: SVs with 1KGP allele freq <=0.01
    awk -F'\t' -v afcol=$afcol 'BEGIN{OFS="\t"} NR==1 || $afcol<=0.01 {print}' \
     $input > "${output}_RESULTS_0.01.tsv"
}

filterInheritance() {
    local input=$1
    local output=$2
    local runtype=$3

    if [[ $runtype == "TRIO" ]]
    then    
        afcol=22
        incol=8

        ##Filtered output 3: de novo SVs
        awk -F'\t' -v inheritance=$incol 'BEGIN{OFS="\t"} NR==1 || $inheritance=="de_novo" {print}' \
        $input > "${output}_RESULTS_denovo.tsv"

    else
        afcol=18
        incol=8

        awk -F'\t' -v inheritance=$incol 'BEGIN{OFS="\t"} NR==1 || $inheritance=="not_inherited" {print}' \
        $input > "${output}_RESULTS_not_inherited.tsv"
    fi

    ##Filtered output 1: SVs absent from 1KGP entirely (afcol = Allele_Freq_ALL_1KGP)
    awk -F'\t' -v afcol=$afcol 'BEGIN{OFS="\t"} NR==1 || $afcol==0 {print}' \
     $input > "${output}_RESULTS_unique.tsv"

    ##Filtered output 2: SVs with 1KGP allele freq <=0.01
    awk -F'\t' -v afcol=$afcol 'BEGIN{OFS="\t"} NR==1 || $afcol<=0.01 {print}' \
     $input > "${output}_RESULTS_0.01.tsv"

     
}

clipRegion() {
    local input=$1
    local output=$2

    inputext=${input##*.}

    if [[ $inputext != "gz" ]]
    then
        if [[ $inputext == "bed" || $inputext == "vcf" ]]
        then
            filename=${input##*/}
            cp $input $temp.${filename}
            bgzip $temp.${filename}
            tabix -p $inputext $temp.${filename}.gz
            cleaninput=$temp.${filename}.gz
            filetype=$inputext
        else
            echo "file input type $inputext can't be used with needLR"
            exit 1
        fi
    else
        cleaninput=$input
        originalfile=${input%*.gz}
        filetype=${originalfile##*.}
        if [[ $filetype != "bed" && $filetype != "vcf" ]]
        then
            echo "file input type $inputext can't be used with needLR"
            exit 1
        fi
    fi

    if [[ ${output##*.} != "gz" ]]
    then
        cleanoutput=$output.gz
    else
        cleanoutput=$output
    fi

    tabix -h $cleaninput ${ANALYSISREGION} > ${cleanoutput%*.gz}
    if [[ $filetype == "vcf" ]]
    then
        bgzip ${cleanoutput%*.gz}
        tabix -p $filetype ${cleanoutput}
    fi

}


############ subcommands ##################
annotateRun() {
    controlstring="1kg"
    if [[ $run1kg -eq 0 ]]
    then
        controlstring="customControl"
    fi

    if [[ ${ANALYSISREGION} != "All" ]]
    then
        echo "CTRL_MERGED is ${CTRL_MERGED}"
        clipRegion ${CTRL_MERGED} $temp.clippedControl.vcf.gz
        CTRL_MERGED=$temp.clippedControl.vcf.gz
    fi
    
    for query in ${INPUT_VCFS[@]}
    do
        echo "Beginning NeedLR annotation of $query"


        FNAME=$(basename "$query" .vcf.gz)_needLR_${controlstring}_v4.0
        QUERY_ID=$(basename "$query" .vcf.gz)
        ##This is the output directory specific to each query VCF
        UNSOLVED_DIR="$OUTPUTDIR/$FNAME"
        mkdir -p "${UNSOLVED_DIR}"
        output="${UNSOLVED_DIR}/$(basename ${query} .vcf.gz).needLR.$version.intermediate"
        finalOutput="${UNSOLVED_DIR}/$(basename ${query} .vcf.gz).needLR.$version"
        
        if [[ ${ANALYSISREGION} != "All" ]]
        then
            clipRegion ${query} $temp.${query##*/}
            analysisquery=$temp.${query##*/}
        else
            analysisquery=$query
        fi

        if [ ! -z ${COHORT_VCF+x} ]
        then
            echo "Annotating as a cohort"
            cohortControlOverlap ${analysisquery} ${output}
            n="${#COHORT_SAMPLE_NAME_LIST[@]}"
            keepcol=0
        else
            echo "Annotating as a single sample"
            singleVCFControlOverlap ${analysisquery} ${output}
            n=1
            keepcol=1
        fi

        annotateGenes "${output}_summarized.txt" ${output}
        
        geneField=$(head -n1 ${output}_genes.txt| awk '{print NF}')
        let indexField=$geneField-1

        geneIndexedAnnotations ${output}_genes.txt ${output} $geneField $indexField

        positionIndexedAnnotations ${output}_filled.txt ${output}

        printTable ${output}_posannotations.txt ${output} ${finalOutput} "$n"
        printVCF $analysisquery ${finalOutput}_RESULTS.tsv ${output} ${finalOutput} "$n"

        filterTable ${finalOutput}_RESULTS.tsv ${finalOutput}

        echo "Completed NeedLR annotation of ${query}"
        echo "Cleaning up"
        rm ${output}*

        echo -e """\nFiles saved to: \n$(ls $finalOutput*)
        """
    done
}

comparatorRun() {

    controlstring="1kg"
    if [[ $run1kg -eq 0 ]]
    then
        controlstring="customControl"
    fi

    ctype=DUO
    #additional subcommand specific validation
    if [ -z ${PARENTALVCFS+x} ]
    then
        echo "At least one parental vcf is required"
        echo ""
        comparatorHelp
        exit 1
    fi
    PARENTALVCFLIST=( $(echo ${PARENTALVCFS} | tr ',' ' ') )
    if [ "${#PARENTALVCFLIST[@]}" -gt 1 ]
    then
        ctype=TRIO
    fi
    echo ${PARENTALVCFLIST[@]}
    validatedParentalVcfs=()
    for vcf in ${PARENTALVCFLIST[@]}
    do
        validatedParentalVcfs+=( $(validateVCF $vcf ) )
    done

    echo """        Parental VCFs :   ${validatedParentalVcfs[@]}"""
    echo """        Comparator Run :  $ctype"""
    echo ""

    if [[ ${ANALYSISREGION} != "All" ]]
    then
        clipRegion ${CTRL_MERGED} $temp.clippedControl.vcf.gz
        CTRL_MERGED=$temp.clippedControl.vcf.gz
    fi

    query=${INPUT_VCFS[0]} # query is proband input
    echo "Beginning $ctype NeedLR annotation of $query"
    FNAME=$(basename "$query" .vcf.gz)_needLR_${ctype}_${controlstring}_v4.0
    QUERY_ID=$(basename "$query" .vcf.gz)
    ##This is the output directory specific to each query VCF
    UNSOLVED_DIR="$OUTPUTDIR/$FNAME"
    mkdir -p "${UNSOLVED_DIR}"
    output="${UNSOLVED_DIR}/$(basename ${query} .vcf.gz).needLR.$version.intermediate"
    finalOutput="${UNSOLVED_DIR}/$(basename ${query} .vcf.gz).needLR.$version"
    
    if [[ ${ANALYSISREGION} != "All" ]]
    then
        allfiles=( ${query} ${validatedParentalVcfs[@]})
        for infile in ${allfiles[@]}
        do
            clipRegion ${infile} $temp.${infile##*/}
        done
        analysisquery=$temp.${query##*/}
        analysisParentalVcfs=( $temp.${validatedParentalVcfs[0]##*/} )
        if [[ ${#validatedParentalVcfs[@]} -gt 1 ]]
        then
            analysisParentalVcfs+=( $temp.${validatedParentalVcfs[1]##*/} )
        fi

    else
        analysisquery=$query
        analysisParentalVcfs=( ${validatedParentalVcfs[@]} )
    fi

    bcftools reheader -n Proband -o ${output}_proband.vcf.gz $analysisquery
    tabix -p vcf ${output}_proband.vcf.gz

    #if this is a duo we want to keep two genotypes
    if [[ $ctype == "TRIO" ]]
    then
        COHORT_SAMPLE_NAME_LIST=(Proband Maternal Paternal )
        bcftools reheader -n Maternal -o ${output}_maternal.vcf.gz ${analysisParentalVcfs[0]}
        tabix -p vcf ${output}_maternal.vcf.gz
        bcftools reheader -n Paternal -o ${output}_paternal.vcf.gz ${analysisParentalVcfs[1]}
        tabix -p vcf ${output}_paternal.vcf.gz

        parentString=${output}_maternal.vcf.gz,${output}_paternal.vcf.gz
        n=3
    else
        COHORT_SAMPLE_NAME_LIST=(Proband Parental )
        bcftools reheader -n Parental -o ${output}_parental.vcf.gz ${analysisParentalVcfs[0]}
        tabix -p vcf ${output}_parental.vcf.gz

        parentString=${output}_parental.vcf.gz
        n=2
    fi

    echo "Annotating as a $ctype"

    multiVCFControlOverlap ${output}_proband.vcf.gz,${parentString} ${output} ${n}

    annotateGenes "${output}_inheritance.txt" ${output}
    
    geneField=$(head -n1 ${output}_genes.txt| awk '{print NF}')
    let indexField=$geneField-1

    geneIndexedAnnotations ${output}_genes.txt ${output} $geneField $indexField

    positionIndexedAnnotations ${output}_filled.txt ${output}

    ## add back in the proband read depths and totals + parental genotypes
    ## remove records with no proband gt
    paste <( cut -f1-9 ${output}_posannotations.txt) \
        ${output}_dvdr.txt \
        <(cut -f17- ${output}_posannotations.txt) \
        | grep -v "not_present" > ${output}_fullwidth.txt

    printTable ${output}_fullwidth.txt ${output} ${finalOutput} $n
    printVCF $analysisquery ${finalOutput}_RESULTS.tsv ${output} ${finalOutput} $n

    

    filterInheritance ${finalOutput}_RESULTS.tsv ${finalOutput} $ctype

    echo "Completed NeedLR annotation of ${query}"
    echo "Cleaning up"
    rm ${output}*

    echo -e """\nFiles saved to: \n$(ls $finalOutput*)
    """
}

bedRun() {
    #additional subcommand specific validation
    if [ ${#INPUT_BEDS[@]} -lt 1 ]
    then
        echo "needLR bed requires bed file input"
        echo ""
        bedHelp
        exit 1
    fi
    for query in ${INPUT_BEDS[@]}
    do
        echo "Beginning NeedLR bed annotation of $query"
        FNAME=$(basename "$query" .bed)_needLR_bed_v4.0
        QUERY_ID=$(basename "$query" .bed)
        ##This is the output directory specific to each query VCF
        UNSOLVED_DIR="$OUTPUTDIR/$FNAME"
        mkdir -p "${UNSOLVED_DIR}"
        output="${UNSOLVED_DIR}/$(basename ${query} .bed).needLR.$version.intermediate"
        finalOutput="${UNSOLVED_DIR}/$(basename ${query} .bed).needLR.$version"

        if [[ ${ANALYSISREGION} != "All" ]]
        then
            clipRegion ${query} $temp.${query##*/}
            analysisquery=$temp.${query##*/}
        else
            analysisquery=$query
        fi

        ncols=$( head -n1 $analysisquery | awk '{print NF}')
        bedheader=( $(head -n1 $analysisquery) )
        if [[ ${bedheader[0]} =~ '#' ]]
        then
            cat $analysisquery | \
                awk 'NR>1{diff=$3-$2;if(diff> -10000000 && diff < 10000000){print $0}}' > ${output}_temp1.txt
            hasheader=1
        else
            cat $analysisquery | \
                awk '{diff=$3-$2;if(diff> -10000000 && diff < 10000000){print $0}}' > ${output}_temp1.txt
            hasheader=0
        fi

        annotateGenes "${output}_temp1.txt" ${output}
        
        geneField=$(head -n1 ${output}_genes.txt| awk '{print NF}')
        let indexField=$geneField-1

        geneIndexedAnnotations ${output}_genes.txt ${output} $geneField $indexField

        positionIndexedAnnotations ${output}_filled.txt ${output}

        if [[ $hasheader -eq 0 ]]
        then
            header=( '#CHROM' START END )
            for((i=3;i<$ncols;i++))
            do
                header+=( "column"$i )
            done
        else
            header=( ${bedheader[@]} )
        fi

        annocols=( $(printAnnotationHeader) )
        header+=( Genes ${annocols[@]:1} )

        echo ${header[@]} | tr ' ' '\t' > ${finalOutput}.bed

        cat ${output}_posannotations.txt >> ${finalOutput}.bed
        echo "Cleaning up"
        rm ${output}*

        echo -e """\nFiles saved to: \n$(ls $finalOutput*)
        """
        
    done
}

# here is where it runs


############################# main  #######################################################################################

case "${subcommand}" in
    annotate) annotateRun ;;
    comparator) comparatorRun ;;
    bed) bedRun ;;
    *) echo "needLR command $subcommand not recognized, exiting"
        help
        exit 1
esac

rm $temp*
